### ISSUE TITLE
Operation timeout issues from tornado

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/mybinder.org-deploy#1323]
We've been having a few operation timeouts causing internal server errors.

This is mostly being reported from the Turing federation cluster, but has also been reported on a different endpoint so could be a more widespread issue which is just reported more often from the Turing cluster.

```
[E 200122 16:22:07 web:1621] Uncaught exception GET /build/gh/ipython/ipython-in-depth/master?binder_launch_host=https%3A%2F%2Fmybinder.org%2F (xxx.xxx.xx.xxx)
    HTTPServerRequest(protocol='https', host='turing.mybinder.org', method='GET', uri='/build/gh/ipython/ipython-in-depth/master?binder_launch_host=https%3A%2F%2Fmybinder.org%2F', version='HTTP/1.1', remote_ip='xxx.xxx.xx.xxx')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/binderhub/builder.py", line 293, in get
        image_manifest = await self.registry.get_image_manifest(*'/'.join(image_name.split('/')[-2:]).split(':', 1))
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.6/site-packages/binderhub/registry.py", line 218, in get_image_manifest
        resp = yield client.fetch(req)
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
    tornado.curl_httpclient.CurlError: HTTP 599: Operation timed out after 20001 milliseconds with 0 bytes received
```

**Comment by sgibson91** [comment]
What do we think about the below hotfix?

```python
        if self.settings['use_registry']:
            image_manifest = await self.registry.get_image_manifest(*'/'.join(image_name.split('/')[-2:]).split(':', 1))
            image_found = bool(image_manifest)
            for _ in range(3):
                try:
                    image_manifest = await self.registry.get_image_manifest(*'/'.join(image_name.split('/')[-2:]).split(':', 1))
                    image_found = bool(image_manifest)
                    break
                except:
                    image_found = False
                    pass
        else:
            # Check if the image exists locally!
            # Assume we're running in single-node mode or all binder pods are assigned to the same node!
            docker_client = docker.from_env(version='auto')
            try:
                docker_client.images.get(image_name)
            except docker.errors.ImageNotFound:
                # image doesn't exist, so do a build!
                image_found = False
            else:
                image_found = True
```

**Comment by betatim** [comment]
Retrying sounds like a good idea. However we should try and `except` only the timeout(?) exception we expect and let everything else cause an error.

**Comment by sgibson91** [comment]
PR opened at https://github.com/jupyterhub/binderhub/pull/1049
