### ISSUE TITLE
OVH etcd has run out of space

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#1557]
OVH has been broken over night and I see the following in the log of the binderhub pod:
```
E 2020-08-01 04:23:15.863 JupyterHub gen:599] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py:845> exception=ApiException()> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 593, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 852, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 656, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 560, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1801, in _start
        pod,
      File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1560, in asynchronize
        return method(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 6115, in create_namespaced_pod
        (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 6206, in create_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 334, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 168, in __call_api
        _request_timeout=_request_timeout)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 377, in request
        body=body)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 266, in POST
        body=body)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request
        raise ApiException(http_resp=r)
    kubernetes.client.rest.ApiException: (500)
    Reason: error
    HTTP response headers: HTTPHeaderDict({'Audit-Id': '5b9eaaec-73e4-4430-895f-45960f523640', 'Content-Type': 'application/json', 'Date': 'Sat, 01 Aug 2020 04:23:15 GMT', 'Content-Length': '154'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"rpc error: code = Unknown desc = ETCD storage quota exceeded","code":500}
```
@mael-le-gal could you take a look at what needs fixing/restarting? I think the k8s etccd is beyond our reach

**Comment by mael-le-gal** [comment]
checking that

**Comment by mael-le-gal** [comment]
I'll check which the k8s team about a possible incident on saturday but this morning everything seems OK to me :

https://mybinder-sre.readthedocs.io/en/latest/operation_guide/federation.html

**Comment by mael-le-gal** [comment]
When you do a `kb get configmap -n kube-system` there is a helm history of 55 `configmap`.
Each one of these configmap is huge and this is probably taking a lot of space in the ETC.
I think keeping only a historic of 5 release would be better. What do you think ?

**Comment by betatim** [comment]
Closing for now as it seems to have resolved itself.
