### ISSUE TITLE
Upgrade failure of daemonsets: dind and image-cleaner, on a specific node

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#1737]
A helm2 -> helm3 transition on prod worked fine in many ways, but restarting dind and image-cleaner turned out a bit problematic. Below I provide some logs of relevance but as I note that the errorings pods came from the same node, I also also inspected the k8s Events related to that node and found this.

```
  Type     Reason      Age   From            Message
  ----     ------      ----  ----            -------
  Warning  OOMKilling  50m   kernel-monitor  Memory cgroup out of memory: Kill process 1689494 (python) score 1943 or sacrifice child
Killed process 1689494 (python) total-vm:3887064kB, anon-rss:1976596kB, file-rss:16116kB, shmem-rss:0kB
  Warning  NodeSysctlChange    27m (x2 over 6h27m)  sysctl-monitor  {"unmanaged": {"net.ipv4.tcp_fastopen_key": "cc28e282-cc64df53-ec94ce54-ef86d970"}}
  Normal   NodeNotSchedulable  3s                   kubelet         Node gke-prod-user-202009-b9c03ca0-cphm status is now: NodeNotSchedulable
```

I guessed that it was no coincidence but could also find another node with the `sysctl-monitor  {"unmanaged": ...` warning so I'm really not sure.

## prod-dind-rn5zb on node gke-prod-user-202009-b9c03ca0-cphm

```
time="2020-12-06T18:36:46.432649056Z" level=info msg="Starting up"
time="2020-12-06T18:36:46.434126429Z" level=warning msg="could not change group /var/run/dind/docker.sock to docker: group docker not found"
failed to load listeners: can't create unix socket /var/run/dind/docker.sock: is a directory
```

## prod-image-cleaner-99jbz on node gke-prod-user-202009-b9c03ca0-cphm

```
2020-12-06 18:41:36,985 Pruning docker images when /var/lib/docker has 80.0% inodes or blocks used
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 207, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/image-cleaner.py", line 255, in <module>
    main()
  File "/usr/local/bin/image-cleaner.py", line 161, in main
    client = docker.from_env(version='auto')
  File "/usr/local/lib/python3.8/site-packages/docker/client.py", line 84, in from_env
    return cls(
  File "/usr/local/lib/python3.8/site-packages/docker/client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 190, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
```

**Comment by betatim** [comment]
The "can't mount docker socket" problem looks like https://mybinder-sre.readthedocs.io/en/latest/operation_guide/common_problems.html#the-docker-in-docker-socket. We haven't had this happen in a long time. I don't think we ever figured out why/when exactly it happens but the fix is easy to apply.
