### ISSUE TITLE
analytics-publisher broken on staging as of recently

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#2234]
```
analytics-publisher-5bbb687666-w9x6f                         0/1     CrashLoopBackOff   17         63m
```

```python-traceback
Traceback (most recent call last):
  File "/srv/run.py", line 8, in <module>
    from indexer import index_events
  File "/srv/indexer.py", line 17, in <module>
    import jinja2
  File "/usr/local/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/markupsafe/__init__.py)
```

I assume what has happened is that we rebuilt the image, and now got a dependency of a modern version, and things broke.

**Comment by consideRatio** [comment]
I'll work to fix this properly.

**Comment by minrk** [comment]
switching to pip-compile should fix it. The analytics-publisher has strict pins of only direct dependencies - an absolute guarantee for broken envs.

**Comment by consideRatio** [comment]
@minrk yepp, doing that!

**Comment by consideRatio** [comment]
#2240 is opened to systematically use requirements.in etc.
