### ISSUE TITLE
Staging deploy fails, blocking production deploys

### ISSUE THREAD

**Issue by manics** [jupyterhub/mybinder.org-deploy#2617]
The staging deployment currently fails, which means production deploys are blocked. e.g.

https://github.com/jupyterhub/mybinder.org-deploy/actions/runs/4853267242/jobs/8649318894

**Comment by manics** [comment]
It's a genuine error:
```
[I 230501 19:18:53 health:152] Checking registry status
[I 230501 19:18:53 health:222] Getting pod statistics for staging
[E 230501 19:18:53 web:1798] Uncaught exception GET /health (5.181.245.119)
    HTTPServerRequest(protocol='https', host='gke.staging.mybinder.org', method='GET', uri='/health', version='HTTP/1.1', remote_ip='<IP>')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/binderhub/health.py", line 200, in get
        overall, checks = await self.check_all()
                          ^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/binderhub/health.py", line 185, in check_all
        await asyncio.gather(*checks.values()), checks.keys()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/binderhub/health.py", line 254, in _check_pod_quotas
        quota = self.settings["launch_quota"].total_pods
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'KubernetesLaunchQuota' object has no attribute 'total_pods'
```
Related to https://github.com/jupyterhub/binderhub/pull/1682

We should figure out whether this could've been picked up in an existing CI check.

**Comment by manics** [comment]
Some tests in the BinderHub PR https://github.com/jupyterhub/binderhub/pull/1682 failed:
https://github.com/jupyterhub/binderhub/actions/runs/4833556899/jobs/8613703568
![image](https://user-images.githubusercontent.com/1644105/235518291-bf3a4022-b4ef-4353-95bd-df476736fa39.png)

But since the tests ended up hitting the GitHub workflow timeout they were marked as ! instead of ❌.

**Comment by manics** [comment]
Fixed by https://github.com/jupyterhub/mybinder.org-deploy/pull/2620
