### ISSUE TITLE
/test-this-pr comment automation broken

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#2639]
We have a comment command based on automation setup in a github workflow:

https://github.com/jupyterhub/mybinder.org-deploy/blob/7602651eb8096838353a2dd9c1abce3fb642ac7c/.github/workflows/test-this-pr.yml#L1-L22

This action failed like below [in this github job](https://github.com/jupyterhub/mybinder.org-deploy/actions/runs/5066975013/jobs/9097433919) triggered for https://github.com/jupyterhub/mybinder.org-deploy/pull/2638.

```
/usr/bin/docker run --name ed8[6](https://github.com/jupyterhub/mybinder.org-deploy/actions/runs/5066975013/jobs/9097433919#step:3:7)6e9f8bd04d0cef4f2[7](https://github.com/jupyterhub/mybinder.org-deploy/actions/runs/5066975013/jobs/9097433919#step:3:8)8ad250e9d8318bae_2ec08b --label ed866e --workdir /github/workspace --rm -e "INPUT_ACCESS_TOKEN" -e "INPUT_REPOSITORY" -e "INPUT_PR_NUMBER" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/mybinder.org-deploy/mybinder.org-deploy":"/github/workspace" ed866e:9f8bd04d0cef4f278ad250e9d8318bae  "***" "jupyterhub/mybinder.org-deploy" "2638"
Traceback (most recent call last):
  File "/app/src/main.py", line 50, in <module>
    post_request(branch_ref_url, headers=HEADER, json=body)
  File "/app/src/utils.py", line 57, in post_request
    raise RuntimeError(resp.text)
RuntimeError: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/git#create-a-reference"}
```

**Comment by minrk** [comment]
fwiw, we are getting a 404 [here](https://github.com/sgibson91/test-this-pr-action/blob/4fd82d9a14d1ed35189db288d7b369a2c5f89643/src/main.py#L50), attempting to create the test-this-pr branch/2638 branch. It's unclear what the 404 would refer to as being not found, as the docs [do not list 404 as an available error code](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference--parameters).

Last successful run appears to have been #2611 on April 28, which is also a PR from a fork, as are ~all previous invocations of this bot.
