### ISSUE TITLE
Failed to connect to event stream on many repos (that used to work)

### ISSUE THREAD

**Issue by ozak** [jupyterhub/mybinder.org-deploy#2929]
### A link to the repository
https://github.com/SMU-Econ-Growth/EconGrowthUG-binder

https://github.com/ozak/CompEcon

### Why are you concerned this repository maybe liable for banning?

For example: it will have lots of users, it makes a lot of API calls, creates a lot of network traffic?

No concerns really

**Comment by ozak** [comment]
These stopped working without any changes to the `environment.yml` files. I am also having the same issue with newer repos like [this one](https://github.com/jjgecon/Replication_Dickens_2022).

**Comment by rgaiacs** [comment]
I confirm that https://github.com/SMU-Econ-Growth/EconGrowthUG-binder is failing to build on GESIS server.

The user log is

```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockervm3nxot_'...
HEAD is now at 18edf19 Update dockerfile-github.yml
Using DockerBuildPack builder
Step 1/11 : FROM condaforge/mambaforge
Fetching base image...
Fetching base image...
 ---> 2723f21d927d
Step 2/11 : RUN apt update
 ---> Running in 572c0a33dc51
[91m
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

[0mGet:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:5 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [3263 kB]
Get:6 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1176 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [29.7 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [3375 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [3413 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [32.4 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3853 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1473 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
Fetched 30.1 MB in 3s (10.1 MB/s)
Reading package lists...
Building dependency tree...
Reading state information...
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
 ---> Removed intermediate container 572c0a33dc51
 ---> 3684983b8faa
Step 3/11 : ENV PROJ_LIB "/opt/conda/share/proj"
 ---> Running in c175f5bf4ebf
 ---> Removed intermediate container c175f5bf4ebf
 ---> fb11464e4441
Step 4/11 : RUN conda install mamba -y -c conda-forge --override-channels
 ---> Running in 3d4ec2b2eb9b
Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): ...working... [91mKilled
[0m ---> Removed intermediate container 3d4ec2b2eb9b
The command '/bin/sh -c conda install mamba -y -c conda-forge --override-channels' returned a non-zero code: 137
```

The build pod log is

```
{"message": "Step 3/11 : ENV PROJ_LIB \"/opt/conda/share/proj\"", "phase": "building"}
{"message": "\n", "phase": "building"}
{"message": " ---> Running in c175f5bf4ebf\n", "phase": "building"}
{"message": " ---> Removed intermediate container c175f5bf4ebf\n", "phase": "building"}
{"message": " ---> fb11464e4441\n", "phase": "building"}
{"message": "Step 4/11 : RUN conda install mamba -y -c conda-forge --override-channels", "phase": "building"}
{"message": "\n", "phase": "building"}
{"message": " ---> Running in 3d4ec2b2eb9b\n", "phase": "building"}
{"message": "Channels:\n - conda-forge\nPlatform: linux-64\nCollecting package metadata (repodata.json): ...working... ", "phase": "building"}
{"message": "\u001b[91mKilled\n\u001b[0m", "phase": "building"}
{"message": " ---> Removed intermediate container 3d4ec2b2eb9b\n", "phase": "building"}
{"message": "The command '/bin/sh -c conda install mamba -y -c conda-forge --override-channels' returned a non-zero code: 137", "phase": "failed"}
Exception ignored in: <function Application.__del__ at 0x7fbb70881090>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/traitlets/config/application.py", line 1065, in __del__
  File "/usr/lib/python3.10/site-packages/traitlets/config/application.py", line 1054, in close_handlers
  File "/usr/lib/python3.10/site-packages/traitlets/traitlets.py", line 687, in __get__
  File "/usr/lib/python3.10/site-packages/traitlets/traitlets.py", line 666, in get
TypeError: 'NoneType' object is not callable
```

I don't know why `conda install mamba -y -c conda-forge --override-channels` is failing.

**Comment by manics** [comment]
```
Step 1/11 : FROM condaforge/mambaforge
```
Doesn't this already include mamba? Maybe conda is having problems when trying to overwrite the default mamba?

**Comment by rgaiacs** [comment]
This can no longer be reproduced.

https://mybinder.org/v2/gh/SMU-Econ-Growth/EconGrowthUG-binder/HEAD shows, in the log,

```
Found built image, launching...
Launching server...
Server requested
2024-08-01T08:22:22.131775Z [Normal] Successfully assigned gesis/jupyter-smu-2decon-2dgrowth-2dgrowthug-2dbinder-2dttlosjaz to spko-css-app03
2024-08-01T08:22:23Z [Normal] Container image "quay.io/jupyterhub/k8s-network-tools:3.3.7" already present on machine
2024-08-01T08:22:23Z [Normal] Created container block-cloud-metadata
2024-08-01T08:22:23Z [Normal] Started container block-cloud-metadata
2024-08-01T08:22:24Z [Normal] Pulling image "gesiscss/binder-r2d-g5b5b759-smu-2decon-2dgrowth-2decongrowthug-2dbinder-f4559c:50aa6299c4de6516236b73413c570e9e7933064f"
```
