### ISSUE TITLE
RStudio sessions broken on newly built repositories

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#865]
Reported here: https://github.com/binder-examples/r_with_python/issues/2#issuecomment-445651765

This is the log from `kubectl` for https://mybinder.org/v2/gh/marskar/r_with_python/master?urlpath=rstudio which is broken:
```
[I 07:44:19.908 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[I 07:44:20.195 NotebookApp] JupyterLab extension loaded from /srv/conda/lib/python3.6/site-packages/jupyterlab
[I 07:44:20.195 NotebookApp] JupyterLab application directory is /srv/conda/share/jupyter/lab
[I 07:44:20.211 NotebookApp] nteract extension loaded from /srv/conda/lib/python3.6/site-packages/nteract_on_jupyter
[I 07:44:20.215 NotebookApp] Will shut down after 600 seconds with no kernels or terminals.
[I 07:44:20.216 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 07:44:20.216 NotebookApp] The Jupyter Notebook is running at:
[I 07:44:20.216 NotebookApp] http://(jupyter-marskar-2dr-5fwith-5fpython-2dtksyb9nu or 127.0.0.1):8888/user/marskar-r_with_python-tksyb9nu/?token=...
[I 07:44:20.216 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 07:44:20.216 NotebookApp] No web browser found: could not locate runnable browser.
[I 07:44:23.401 NotebookApp] 302 GET /user/marskar-r_with_python-tksyb9nu/ (10.12.5.40) 0.72ms
[I 07:44:31.622 NotebookApp] 302 GET /user/marskar-r_with_python-tksyb9nu/rstudio?token=Ws7kkAg8Q5qWLhaBKbf43w (194.230.158.82) 2.05ms
[I 07:44:31.828 NotebookApp] No existing rsession found
[I 07:44:31.829 NotebookApp] Starting process...
[I 07:44:34.191 NotebookApp] rsession startup complete
[E 07:44:34.191 NotebookApp] Uncaught exception GET /user/marskar-r_with_python-tksyb9nu/rstudio/?token=Ws7kkAg8Q5qWLhaBKbf43w (194.230.158.82)
    HTTPServerRequest(protocol='https', host='hub.mybinder.org', method='GET', uri='/user/marskar-r_with_python-tksyb9nu/rstudio/?token=Ws7kkAg8Q5qWLhaBKbf43w', version='HTTP/1.1', remote_ip='194.230.158.82', headers={'Cookie': 'username-hub-mybinder-org="2|1:0|10:1544427871|25:username-hub-mybinder-org|44:ZjNiMGE3NmJkZDkzNGZlMjhmMzc1NzM1NmI5ZTg4OTc=|dcb2029e6c1986bade81123190e63d0b2d7aeb3af0bc004e324a36ee644c1076"; _xsrf=2|73c6f680|da75c32a8e29e8821ac0f730b7f86db0|1542885108', 'Upgrade-Insecure-Requests': '1', 'Dnt': '1', 'Referer': 'https://mybinder.org/v2/gh/marskar/r_with_python/master?urlpath=rstudio', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.5', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:64.0) Gecko/20100101 Firefox/64.0', 'X-Scheme': 'https', 'X-Original-Uri': '/user/marskar-r_with_python-tksyb9nu/rstudio/?token=Ws7kkAg8Q5qWLhaBKbf43w', 'X-Forwarded-Proto': 'https,http', 'X-Forwarded-Port': '443,80', 'X-Forwarded-Host': 'hub.mybinder.org', 'X-Forwarded-For': '194.230.158.82,10.12.5.27', 'X-Real-Ip': '194.230.158.82', 'Connection': 'close', 'Host': 'hub.mybinder.org'})
    Traceback (most recent call last):
      File "/srv/conda/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/srv/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/srv/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/srv/conda/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "<string>", line 6, in _wrap_awaitable
      File "/srv/conda/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 95, in get
        return await self.http_get(*args, **kwargs)
      File "/srv/conda/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 461, in http_get
        return await self.proxy(self.port, path)
      File "/srv/conda/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 440, in proxy
        return await super().proxy(self.port, path)
      File "/srv/conda/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 242, in proxy
        url_path_join(self.base_url, 'proxy', port)
      File "/srv/conda/lib/python3.6/site-packages/notebook/utils.py", line 46, in url_path_join
        final = pieces[-1].endswith('/')
    AttributeError: 'int' object has no attribute 'endswith'
[E 07:44:34.229 NotebookApp] {
      "Cookie": "username-hub-mybinder-org=\"2|1:0|10:1544427871|25:username-hub-mybinder-org|44:ZjNiMGE3NmJkZDkzNGZlMjhmMzc1NzM1NmI5ZTg4OTc=|dcb2029e6c1986bade81123190e63d0b2d7aeb3af0bc004e324a36ee644c1076\"; _xsrf=2|73c6f680|da75c32a8e29e8821ac0f730b7f86db0|1542885108",
      "Upgrade-Insecure-Requests": "1",
      "Dnt": "1",
      "Referer": "https://mybinder.org/v2/gh/marskar/r_with_python/master?urlpath=rstudio",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:64.0) Gecko/20100101 Firefox/64.0",
      "X-Scheme": "https",
      "X-Original-Uri": "/user/marskar-r_with_python-tksyb9nu/rstudio/?token=Ws7kkAg8Q5qWLhaBKbf43w",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.mybinder.org",
      "X-Forwarded-For": "194.230.158.82,10.12.5.27",
      "X-Real-Ip": "194.230.158.82",
      "Connection": "close",
      "Host": "hub.mybinder.org"
    }
[E 07:44:34.229 NotebookApp] 500 GET /user/marskar-r_with_python-tksyb9nu/rstudio/?token=Ws7kkAg8Q5qWLhaBKbf43w (194.230.158.82) 2402.79ms referer=https://mybinder.org/v2/gh/marskar/r_with_python/master?urlpath=rstudio
```

This is the full log from running http://mybinder.org/v2/gh/binder-examples/r_with_python/master?urlpath=rstudio which works (but we should check on those errors):
```
[I 07:33:15.140 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[I 07:33:15.977 NotebookApp] JupyterLab extension loaded from /srv/conda/lib/python3.6/site-packages/jupyterlab
[I 07:33:15.978 NotebookApp] JupyterLab application directory is /srv/conda/share/jupyter/lab
[I 07:33:16.018 NotebookApp] nteract extension loaded from /srv/conda/lib/python3.6/site-packages/nteract_on_jupyter
[I 07:33:16.021 NotebookApp] Will shut down after 600 seconds with no kernels or terminals.
[I 07:33:16.022 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 07:33:16.022 NotebookApp] The Jupyter Notebook is running at:
[I 07:33:16.022 NotebookApp] http://(jupyter-binder-2dexamples-2dr-5fwith-5fpython-2dyo57271z or 127.0.0.1):8888/user/binder-examples-r_with_python-yo57271z/?token=...
[I 07:33:16.022 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 07:33:16.023 NotebookApp] No web browser found: could not locate runnable browser.
[I 07:33:36.221 NotebookApp] 302 GET /user/binder-examples-r_with_python-yo57271z/ (10.12.5.40) 1.03ms
[I 07:33:42.182 NotebookApp] 302 GET /user/binder-examples-r_with_python-yo57271z/rstudio?token=EzRQ6yr6QIauFYl-Fx6K4Q (194.230.155.208) 1.55ms
[I 07:33:42.544 NotebookApp] No existing rsession found
[I 07:33:42.545 NotebookApp] Starting process...
[I 07:33:47.874 NotebookApp] rsession startup complete
[E 07:34:16.024 NotebookApp] Exception in callback <bound method NotebookApp.shutdown_no_activity of <notebook.notebookapp.NotebookApp object at 0x7fd9858624e0>>
    Traceback (most recent call last):
      File "/srv/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 1026, in _run
        return self.callback()
      File "/srv/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1579, in shutdown_no_activity
        (utcnow() - self.web_app.last_activity()).total_seconds()
      File "/srv/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 372, in last_activity
        return max(sources)
    TypeError: can't compare offset-naive and offset-aware datetimes
[E 07:34:56.815 NotebookApp] {
      "Cookie": "username-hub-mybinder-org=\"2|1:0|10:1544427222|25:username-hub-mybinder-org|44:ZjM4MmZjMDU1ZTk5NGQ3N2FkN2NmYTU2ODg3NTY5MDA=|247268bc5f8832a2cf0bb7ce148ff5cc2f5c4655664e94b68af4ec43660f02fb\"; _xsrf=2|73c6f680|da75c32a8e29e8821ac0f730b7f86db0|1542885108",
      "Dnt": "1",
      "X-Rs-Rid": "-2035122710",
      "Content-Type": "application/json",
      "Referer": "https://hub.mybinder.org/user/binder-examples-r_with_python-yo57271z/rstudio/?token=EzRQ6yr6QIauFYl-Fx6K4Q",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:64.0) Gecko/20100101 Firefox/64.0",
      "Content-Length": "148",
      "X-Scheme": "https",
      "X-Original-Uri": "/user/binder-examples-r_with_python-yo57271z/rstudio/events/get_events",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.mybinder.org",
      "X-Forwarded-For": "194.230.155.208,10.12.5.27",
      "X-Real-Ip": "194.230.155.208",
      "Connection": "close",
      "Host": "hub.mybinder.org"
    }
[E 07:34:56.815 NotebookApp] 599 POST /user/binder-examples-r_with_python-yo57271z/rstudio/events/get_events (194.230.155.208) 20010.27ms referer=https://hub.mybinder.org/user/binder-examples-r_with_python-yo57271z/rstudio/?token=EzRQ6yr6QIauFYl-Fx6K4Q
[E 07:35:16.045 NotebookApp] Exception in callback <bound method NotebookApp.shutdown_no_activity of <notebook.notebookapp.NotebookApp object at 0x7fd9858624e0>>
    Traceback (most recent call last):
      File "/srv/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 1026, in _run
        return self.callback()
      File "/srv/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1579, in shutdown_no_activity
        (utcnow() - self.web_app.last_activity()).total_seconds()
      File "/srv/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 372, in last_activity
        return max(sources)
    TypeError: can't compare offset-naive and offset-aware datetimes
[E 07:35:18.895 NotebookApp] {
      "Cookie": "username-hub-mybinder-org=\"2|1:0|10:1544427222|25:username-hub-mybinder-org|44:ZjM4MmZjMDU1ZTk5NGQ3N2FkN2NmYTU2ODg3NTY5MDA=|247268bc5f8832a2cf0bb7ce148ff5cc2f5c4655664e94b68af4ec43660f02fb\"; _xsrf=2|73c6f680|da75c32a8e29e8821ac0f730b7f86db0|1542885108",
      "Dnt": "1",
      "X-Rs-Rid": "-977356812",
      "Content-Type": "application/json",
      "Referer": "https://hub.mybinder.org/user/binder-examples-r_with_python-yo57271z/rstudio/?token=EzRQ6yr6QIauFYl-Fx6K4Q",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:64.0) Gecko/20100101 Firefox/64.0",
      "Content-Length": "149",
      "X-Scheme": "https",
      "X-Original-Uri": "/user/binder-examples-r_with_python-yo57271z/rstudio/events/get_events",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.mybinder.org",
      "X-Forwarded-For": "194.230.155.208,10.12.5.27",
      "X-Real-Ip": "194.230.155.208",
      "Connection": "close",
      "Host": "hub.mybinder.org"
    }
[E 07:35:18.895 NotebookApp] 599 POST /user/binder-examples-r_with_python-yo57271z/rstudio/events/get_events (194.230.155.208) 20008.59ms referer=https://hub.mybinder.org/user/binder-examples-r_with_python-yo57271z/rstudio/?token=EzRQ6yr6QIauFYl-Fx6K4Q
[E 07:35:43.965 NotebookApp] {
      "Cookie": "username-hub-mybinder-org=\"2|1:0|10:1544427222|25:username-hub-mybinder-org|44:ZjM4MmZjMDU1ZTk5NGQ3N2FkN2NmYTU2ODg3NTY5MDA=|247268bc5f8832a2cf0bb7ce148ff5cc2f5c4655664e94b68af4ec43660f02fb\"; _xsrf=2|73c6f680|da75c32a8e29e8821ac0f730b7f86db0|1542885108",
      "Dnt": "1",
      "X-Rs-Rid": "33081434",
      "Content-Type": "application/json",
      "Referer": "https://hub.mybinder.org/user/binder-examples-r_with_python-yo57271z/rstudio/?token=EzRQ6yr6QIauFYl-Fx6K4Q",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "application/json",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:64.0) Gecko/20100101 Firefox/64.0",
      "Content-Length": "149",
      "X-Scheme": "https",
      "X-Original-Uri": "/user/binder-examples-r_with_python-yo57271z/rstudio/events/get_events",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.mybinder.org",
      "X-Forwarded-For": "194.230.155.208,10.12.5.27",
      "X-Real-Ip": "194.230.155.208",
      "Connection": "close",
      "Host": "hub.mybinder.org"
    }
[E 07:35:43.965 NotebookApp] 599 POST /user/binder-examples-r_with_python-yo57271z/rstudio/events/get_events (194.230.155.208) 20031.37ms referer=https://hub.mybinder.org/user/binder-examples-r_with_python-yo57271z/rstudio/?token=EzRQ6yr6QIauFYl-Fx6K4Q
[E 07:36:16.055 NotebookApp] Exception in callback <bound method NotebookApp.shutdown_no_activity of <notebook.notebookapp.NotebookApp object at 0x7fd9858624e0>>
    Traceback (most recent call last):
      File "/srv/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 1026, in _run
        return self.callback()
      File "/srv/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1579, in shutdown_no_activity
        (utcnow() - self.web_app.last_activity()).total_seconds()
      File "/srv/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 372, in last_activity
        return max(sources)
    TypeError: can't compare offset-naive and offset-aware datetimes
[E 07:37:16.082 NotebookApp] Exception in callback <bound method NotebookApp.shutdown_no_activity of <notebook.notebookapp.NotebookApp object at 0x7fd9858624e0>>
    Traceback (most recent call last):
      File "/srv/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 1026, in _run
        return self.callback()
      File "/srv/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1579, in shutdown_no_activity
        (utcnow() - self.web_app.last_activity()).total_seconds()
      File "/srv/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 372, in last_activity
        return max(sources)
    TypeError: can't compare offset-naive and offset-aware datetimes
[E 07:38:16.082 NotebookApp] Exception in callback <bound method NotebookApp.shutdown_no_activity of <notebook.notebookapp.NotebookApp object at 0x7fd9858624e0>>
    Traceback (most recent call last):
      File "/srv/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 1026, in _run
        return self.callback()
      File "/srv/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1579, in shutdown_no_activity
        (utcnow() - self.web_app.last_activity()).total_seconds()
      File "/srv/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 372, in last_activity
        return max(sources)
    TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by betatim** [comment]
```
      File "/srv/conda/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 95, in get
        return await self.http_get(*args, **kwargs)
      File "/srv/conda/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 461, in http_get
        return await self.proxy(self.port, path)
      File "/srv/conda/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 440, in proxy
        return await super().proxy(self.port, path)
      File "/srv/conda/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 242, in proxy
        url_path_join(self.base_url, 'proxy', port)
      File "/srv/conda/lib/python3.6/site-packages/notebook/utils.py", line 46, in url_path_join
        final = pieces[-1].endswith('/')
```
Looks like a recent change in nbserverproxy causes this. We pin the version of nbRsessionproxy in repo2docker but not its dependencies. A recent release of nbserverproxy would fit with the reports that this continues to work on images that were built "about a week ago" but has been broken since.

**Comment by betatim** [comment]
After jupyterhub/nbserverproxy#59 is merged we will also have to release a new version of nbserverproxy. After that rebuilding your repository should fix things.

**Comment by betatim** [comment]
Any thoughts on adding a test like https://github.com/jupyterhub/mybinder.org-deploy/blob/2ae72a6ab3df28346be8fb1499ea8c71bb28f29f/tests/test_build.py#L52 but for a repository that tries to launch RStudio to stop this from coming back?

**Comment by betatim** [comment]
To resolve this:
* [ ] new nbrsessionproxy release on pypi
* [ ] update repo2docker to use that new release
* [ ] deploy new repo2docker version to mybinder.org
* [ ] test that it works with a *newly built* repository

**Comment by consideRatio** [comment]
@betatim if a `nbrsessionproxy` release is made on pypi, does that mean conda is updated also?
